sudo: required
language: generic

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.pyenv
    - googletest
    - swig-3.0.10

matrix:
  include:
  - os: linux
    services: docker
    env: DOCKER_IMAGE=vinther/tickenv:0.2
  - os: osx
    env: TOXENV=py34
  - os: osx
    env: TOXENV=py35

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis_install_mac.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py build_ext --inplace cpptest pytest cpplint; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v `pwd`:/io "$DOCKER_IMAGE" /io/tools/docker/build_wheels.sh; fi

  #- export PYTHONPATH=${PYTHONPATH}:${TRAVIS_BUILD_DIR} && (cd DOC && make doctest)

notifications:
  slack:
    secure: m9B/ZFfTZRZTRT5yVXdHKOfO+f7Nnq5w9sewxMXFe0RQ/jaEFWt2b/jA9gTR1WJKvQ/05hmShMlz7UMCZguXqElYzsLvdribmV94TvmFpJdsoF80palZzzjRCm9lNHx66RWJ4l5p9wKAS+73tafDBBlGwaOqc234le+YxYsTIGgzeb69WS547LkHhbmPTgbhG+k8jAfE0OByXsSmaOTVyqbWerK1WF8KzlGx5WqWkGhECloTBLdcK0+oxelHYGdwI2CCRi/SfOfEyO6ceyV6hqE6Xt0g/RJhO4lEs9ahIVryUKUTpYxbgO0eWJ0LwM0OolfCAaphKHogd4Z6zHGr2EXmkXzElUcT5fMFhSD1/KxBXWxSl3TdAOpzaXG5WTYDV+38rM15FGhQD+q9monR3q7aHs/P7BkAcZBJGns61gTV1R9o+xMV4naMGH7/SRPxS9Jmz6h7Wg6WzoH2E2/Qq0YL+w3BDg6vpXNoBstmX/3D0G7S+SFmQcZqXQ18RGC5HqP1YA0gJyX89Bl8ZRBD4JTplh/Mnb20ORBNt+aaWzGEdOf7DRcGfc0Yl7Wyap92+dvX+wW7KPEUU04uRlKk/FHXA6U3NcsL9Le//+SsPveW7iCMF8e2jct9E5e7kCd2fkiExwH130zfhmDXApTBHVZGjiB/swx0X+utiXkQUbQ=
