
name: Build Tick on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TICK_DEBUG: 0
  TICK_WERROR: 0
  PYTHONUNBUFFERED: 1

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64





    - name: pip
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[dev,plot]

    - name: build
      run: |
        python3 -m build --wheel

    - name: pytest random
      run: |
        python3 -u -X faulthandler -m pytest -x -vv -s -rA --durations=20 --timeout=300 --timeout-method=thread -o console_output_style=progress -o faulthandler_timeout=600 tick/random/tests/random_test.py

    - name: pytest core
      run: |
        python3 -u -X faulthandler -m pytest -x -vv -s -rA --durations=20 --timeout=300 --timeout-method=thread -o console_output_style=progress -o faulthandler_timeout=600 tick/array/tests tick/array_test/tests tick/base/tests tick/base_model/tests tick/dataset/tests tick/linear_model/tests tick/preprocessing/tests tick/prox/tests tick/robust/tests tick/solver/tests

    - name: pytest hawkes
      run: |
        python3 -u -X faulthandler -m pytest -x -vv -s -rA --durations=20 --timeout=300 --timeout-method=thread -o console_output_style=progress -o faulthandler_timeout=600 tick/hawkes

    - name: pytest remaining
      run: |
        python3 -u -X faulthandler -m pytest -x -vv -s -rA --durations=20 --timeout=300 --timeout-method=thread -o console_output_style=progress -o faulthandler_timeout=600 tick/plot/tests tick/survival/tests
